# Generated by Django 3.1.2 on 2020-10-12 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationPracticeAnswerDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chap_No', models.IntegerField()),
                ('Cosentence_answer', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationPracticeQuestionDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chap_No', models.IntegerField()),
                ('Cosentence_question', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='EssentialSentenceDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chap_No', models.IntegerField()),
                ('Essentence_question', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='checkprocess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkprocess', to='auth.user'),
        ),
    ]
