# Generated by Django 3.1.2 on 2020-10-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201012_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterNumberDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chap_No', models.IntegerField()),
            ],
        ),
    ]
