# Generated by Django 3.1.2 on 2020-10-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201017_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationpracticeanswerdb',
            old_name='Chap_No',
            new_name='ChapNo',
        ),
        migrations.AlterField(
            model_name='checkprocess',
            name='chap_1',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='checkprocess',
            name='chap_2',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='checkprocess',
            name='chap_3',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='checkprocess',
            name='chap_4',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='checkprocess',
            name='chap_5',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='checkprocess',
            name='chap_6',
            field=models.IntegerField(default=1),
        ),
    ]
