# Generated by Django 3.1.2 on 2020-10-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20201019_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationpracticeanswerdb',
            name='InnerNo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversationpracticeanswerdb',
            name='SentenceNo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversationpracticequestiondb',
            name='InnerNo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversationpracticequestiondb',
            name='SentenceNo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='essentialsentencedb',
            name='InnerNo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='essentialsentencedb',
            name='SentenceNo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
