# Generated by Django 3.1.2 on 2020-10-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20201019_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapternumberdb',
            name='ChapName',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
